### ISSUE TITLE
Trying to understand your GraphQL schema

### ISSUE THREAD

**Issue by rayoplateado** [cyberbobs/gridsome-image-array-test#1]
Hi. I'm landing here studying a little bit how gridsome works. I've created from zero a super simple blog, and everything seems to be fine.

The point is when I want to add a cover image into my blog posts. By a reason I don't understand, can't use g-image with the img urls on my post md meta data. It seems to be Strings, but g-image expects an object.

Then I found your repo, clone it, and, there it is, your portfolio schema has a cover json field. 

I've checked one by one all the files, trying to replicate what you do over my project, but, seems i've forget something.

Did you do something with your schema? or it was as simple as add cover metadata inside a portfolio markdown file and there you go?

Not sure if understand how things works here... Can you help me out?

Thank you.

**Comment by rayoplateado** [comment]
Hey. Forget it. I've just created an new project and i'm working on getting things done. By now, cover is in schema and what didn't work now works. So anything must be done. Probable something needs to be undone. That's why i'm recreating everything again. I hate not to know what I was doing wrong, but need to move forward.

Thank you!

**Comment by cyberbobs** [comment]
This repo was actually created to reproduce [two](https://github.com/gridsome/gridsome/issues/117) [issues](https://github.com/gridsome/gridsome/issues/118) I've opened in gridsome repo. Turns out only one of them is an issue, other one is just documentation somewhat lacking. See the comments on the issues to find out about a problems I'm talking about and solutions for those.
